version: '3.5'

services:
  leader_postgres:
    container_name: leader_postgres
    image: postgres
    environment:
      POSTGRES_USER: leader
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres0:/data/postgres
    ports:
      - "5430:5432"
    restart: unless-stopped
  node_1_postgres:
    container_name: node_1_postgres
    image: postgres
    environment:
      POSTGRES_USER: node1
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres1:/data/postgres
    ports:
      - "5431:5432"
    restart: unless-stopped
  node_2_postgres:
    container_name: node_2_postgres
    image: postgres
    environment:
      POSTGRES_USER: node2
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres2:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres0:
  postgres1:
  postgres2: